import PDFDocument from "pdfkit";

// Client-facing quotation document, built from the manual line items a
// Manager works out on the Quotations page's Quotation Workspace (see
// quotationLineItems in schema/tasks.ts) - per direct product
// direction: "let's do it manually... now I just need the engine
// build first". No rate lookups here; the amounts are exactly what
// was typed in.
export interface QuotationPdfData {
  task: {
    taskNumber: string;
    title: string;
    venueName: string | null;
    clientName: string;
    clientContact: string;
    clientRequirements: string;
    dueDate: string | null;
    endDate: string | null;
    operatorsRequired: number;
    armedRequired: boolean;
    vehiclesRequired: number;
  };
  lineItems: { description: string; amount: number }[];
  currency: string;
}

function formatMoney(amount: number, currency: string) {
  return `${amount.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ${currency}`;
}

export function buildQuotationPdf(data: QuotationPdfData): PDFKit.PDFDocument {
  const doc = new PDFDocument({ margin: 50, size: "A4" });
  const generatedAt = new Date();
  const total = data.lineItems.reduce((sum, i) => sum + i.amount, 0);

  doc.fontSize(20).font("Helvetica-Bold").text("VenueGuard Quotation");
  doc.moveDown(0.2);
  doc.fontSize(10).font("Helvetica").fillColor("#666666").text(`Quote Reference: ${data.task.taskNumber}`);
  doc.text(`Date: ${generatedAt.toLocaleDateString()}`);
  doc.fillColor("#000000");
  doc.moveDown(0.8);

  doc.fontSize(14).font("Helvetica-Bold").text(data.task.title || "Untitled Task");
  doc.moveDown(0.5);

  doc.fontSize(10).font("Helvetica");
  const metaRows: [string, string][] = [
    ["Client", data.task.clientName || "—"],
    ["Contact", data.task.clientContact || "—"],
    ["Venue", data.task.venueName ?? "Not linked to a venue"],
  ];
  if (data.task.dueDate) metaRows.push(["Start", new Date(data.task.dueDate).toLocaleString()]);
  if (data.task.endDate) metaRows.push(["End", new Date(data.task.endDate).toLocaleString()]);
  metaRows.push([
    "Operators",
    `${data.task.operatorsRequired} operator${data.task.operatorsRequired !== 1 ? "s" : ""}${data.task.armedRequired ? " (Armed)" : " (Unarmed)"}`,
  ]);
  if (data.task.vehiclesRequired > 0) {
    metaRows.push(["Vehicles", `${data.task.vehiclesRequired} vehicle${data.task.vehiclesRequired !== 1 ? "s" : ""}`]);
  }
  for (const [label, value] of metaRows) {
    doc.font("Helvetica-Bold").text(`${label}: `, { continued: true }).font("Helvetica").text(value);
  }

  if (data.task.clientRequirements) {
    doc.moveDown(0.4);
    doc.font("Helvetica-Bold").text("Client Requirements:");
    doc.font("Helvetica").text(data.task.clientRequirements);
  }

  drawSectionRule(doc);
  doc.fontSize(14).font("Helvetica-Bold").text("Quotation");
  doc.moveDown(0.5);

  const tableLeft = doc.page.margins.left;
  const tableRight = doc.page.width - doc.page.margins.right;
  const amountColWidth = 100;
  const descColWidth = tableRight - tableLeft - amountColWidth;

  doc.fontSize(10).font("Helvetica-Bold");
  const headerY = doc.y;
  doc.text("Description", tableLeft, headerY, { width: descColWidth });
  doc.text("Amount", tableLeft + descColWidth, headerY, { width: amountColWidth, align: "right" });
  doc.moveDown(0.3);
  doc.strokeColor("#000000").lineWidth(0.5).moveTo(tableLeft, doc.y).lineTo(tableRight, doc.y).stroke();
  doc.moveDown(0.4);

  doc.font("Helvetica");
  if (data.lineItems.length === 0) {
    doc.fillColor("#999999").text("No line items yet.");
    doc.fillColor("#000000");
  } else {
    for (const item of data.lineItems) {
      const rowY = doc.y;
      doc.text(item.description || "—", tableLeft, rowY, { width: descColWidth });
      const afterDescY = doc.y;
      doc.text(formatMoney(item.amount, data.currency), tableLeft + descColWidth, rowY, { width: amountColWidth, align: "right" });
      doc.y = Math.max(doc.y, afterDescY);
      doc.moveDown(0.3);
    }
  }

  doc.moveDown(0.3);
  doc.strokeColor("#000000").lineWidth(0.5).moveTo(tableLeft, doc.y).lineTo(tableRight, doc.y).stroke();
  doc.moveDown(0.4);

  doc.fontSize(12).font("Helvetica-Bold");
  const totalRowY = doc.y;
  doc.text("Total", tableLeft, totalRowY, { width: descColWidth });
  doc.text(formatMoney(total, data.currency), tableLeft + descColWidth, totalRowY, { width: amountColWidth, align: "right" });

  drawSectionRule(doc);
  doc.fontSize(9).font("Helvetica").fillColor("#999999").text(
    "This quotation is an estimate based on the requirements above and is subject to change. Generated by VenueGuard.",
  );
  doc.fillColor("#000000");

  return doc;
}

function drawSectionRule(doc: PDFKit.PDFDocument) {
  doc.moveDown(0.6);
  const y = doc.y;
  doc
    .strokeColor("#cccccc")
    .lineWidth(1)
    .moveTo(doc.page.margins.left, y)
    .lineTo(doc.page.width - doc.page.margins.right, y)
    .stroke();
  doc.moveDown(0.6);
}
