// Country Intelligence Engine - US State Department Travel Advisory
// reference table.
//
// The live State Department APIs turned out not to expose the actual
// Level 1-4 rating anywhere (CountryTravelInformation has no such
// field - confirmed directly on Afghanistan, a real Level 4 country;
// TravelAdvisories/XMLTravelAdvisories return empty or error), and
// travel.state.gov itself blocks all automated requests with
// Cloudflare bot protection (a real HTTP 403, not a sandbox artifact -
// confirmed via a direct user curl). So there is no reliable live-fetch
// path for this rating.
//
// This table is transcribed directly from the State Department Bureau
// of Consular Affairs' own authoritative ArcGIS feature service (item
// "Travel Advisory Levels (View Layer - Read Only)", id
// 85cf3abbe6ce41298b238cb661ba1ef8, description: "stewarded exclusively
// by authoritative members of OCS [Office of Consular Services]") -
// the same data that drives the official interactive map at
// travel.state.gov/.../traveladvisories.html. Reachable because it's
// hosted on public ArcGIS infrastructure (services6.arcgis.com), not
// behind the .gov domain's bot protection. Pulled via:
//   https://services6.arcgis.com/R6wlO6UHmSzqm9Vs/arcgis/rest/services/
//   Travel_Advisory_Levels_viewOnlyVectors/FeatureServer/0/query
//   ?where=1=1&outFields=NAME,LEVEL_,ADVDATE,URL&returnGeometry=false
//
// Real data, not live - a deliberate tradeoff (per direct product
// direction) given no live path exists. `advisoryDate` is the real,
// per-country date the State Department itself last updated that
// country's advisory (from the feature's own ADVDATE field), shown in
// the UI so this is never presented as more current than it is.
//
// GENERATED FILE - do not hand-edit. Regenerate monthly (or as needed)
// via:
//   pnpm --filter @workspace/scripts run refresh-travel-advisories
// (scripts/src/refresh-travel-advisories.ts). This particular copy was
// transcribed by hand from the same query, before that script existed.
// Last generated: 2026-08-07
//
// LEVEL_ encodes two things: the base 1-4 level, and (values >= 10)
// whether the country "contains areas with higher security risk" (a
// State Dept map legend category, e.g. 20 = Level 2 with higher-risk
// areas) - divided out into `higherRiskAreas` below so callers get a
// plain 1-4 level.
//
// Includes State Dept entries below the country level (Mexican states,
// Gaza Strip, West Bank, etc.) as-is; lookups match by name against our
// own registry, so these are simply never matched rather than filtered
// out here.
export interface TravelAdvisoryRow {
  name: string;
  level: 1 | 2 | 3 | 4;
  higherRiskAreas: boolean;
  advisoryDate: string | null;
}

export const TRAVEL_ADVISORY_LEVELS: TravelAdvisoryRow[] = [
  { name: "Afghanistan", level: 4, higherRiskAreas: false, advisoryDate: "2024-07-29" },
  { name: "Aguascalientes", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Albania", level: 2, higherRiskAreas: true, advisoryDate: "2023-07-13" },
  { name: "Algeria", level: 2, higherRiskAreas: true, advisoryDate: "2024-09-26" },
  { name: "American Samoa", level: 1, higherRiskAreas: false, advisoryDate: null },
  { name: "Andorra", level: 1, higherRiskAreas: false, advisoryDate: "2023-07-26" },
  { name: "Angola", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-23" },
  { name: "Anguilla", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-23" },
  { name: "Antarctica", level: 2, higherRiskAreas: false, advisoryDate: "2022-10-05" },
  { name: "Antigua and Barbuda", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-22" },
  { name: "Argentina", level: 1, higherRiskAreas: false, advisoryDate: "2023-08-18" },
  { name: "Armenia", level: 2, higherRiskAreas: true, advisoryDate: "2024-04-09" },
  { name: "Aruba", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-19" },
  { name: "Australia", level: 1, higherRiskAreas: false, advisoryDate: "2023-09-08" },
  { name: "Austria", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-23" },
  { name: "Azerbaijan", level: 2, higherRiskAreas: true, advisoryDate: "2023-11-02" },
  { name: "Azores", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Bahrain", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-09" },
  { name: "Baja California", level: 3, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Baja California Sur", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Bangladesh", level: 3, higherRiskAreas: true, advisoryDate: "2024-09-11" },
  { name: "Barbados", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-22" },
  { name: "Belarus", level: 4, higherRiskAreas: false, advisoryDate: "2023-07-26" },
  { name: "Belgium", level: 2, higherRiskAreas: false, advisoryDate: "2023-07-26" },
  { name: "Belize", level: 2, higherRiskAreas: true, advisoryDate: "2023-11-13" },
  { name: "Benin", level: 2, higherRiskAreas: true, advisoryDate: "2024-05-24" },
  { name: "Bermuda", level: 1, higherRiskAreas: false, advisoryDate: "2024-11-12" },
  { name: "Bhutan", level: 1, higherRiskAreas: false, advisoryDate: "2024-06-26" },
  { name: "Bolivia", level: 2, higherRiskAreas: true, advisoryDate: "2023-06-06" },
  { name: "Bonaire", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-19" },
  { name: "Bosnia and Herzegovina", level: 2, higherRiskAreas: false, advisoryDate: "2023-07-26" },
  { name: "Botswana", level: 1, higherRiskAreas: false, advisoryDate: "2023-07-31" },
  { name: "Bouvet Island", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Brazil", level: 2, higherRiskAreas: true, advisoryDate: "2023-10-19" },
  { name: "British Indian Ocean Territory", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "British Virgin Islands", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-22" },
  { name: "Brunei Darussalam", level: 1, higherRiskAreas: false, advisoryDate: "2023-12-19" },
  { name: "Bulgaria", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-15" },
  { name: "Burkina Faso", level: 4, higherRiskAreas: false, advisoryDate: "2023-07-31" },
  { name: "Burma", level: 4, higherRiskAreas: false, advisoryDate: "2024-06-06" },
  { name: "Burundi", level: 3, higherRiskAreas: true, advisoryDate: "2023-07-31" },
  { name: "Cabo Verde", level: 1, higherRiskAreas: true, advisoryDate: "2024-09-23" },
  { name: "Cambodia", level: 1, higherRiskAreas: true, advisoryDate: "2023-07-25" },
  { name: "Cameroon", level: 2, higherRiskAreas: true, advisoryDate: "2023-07-31" },
  { name: "Campeche", level: 1, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Canada", level: 1, higherRiskAreas: false, advisoryDate: "2024-10-04" },
  { name: "Canary Islands", level: 2, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Cayman Islands", level: 1, higherRiskAreas: false, advisoryDate: "2024-09-04" },
  { name: "Central African Republic", level: 4, higherRiskAreas: false, advisoryDate: "2023-07-31" },
  { name: "Chad", level: 3, higherRiskAreas: true, advisoryDate: "2023-07-31" },
  { name: "Chiapas", level: 3, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Chihuahua", level: 3, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Chile", level: 2, higherRiskAreas: false, advisoryDate: "2023-07-17" },
  { name: "China", level: 3, higherRiskAreas: false, advisoryDate: "2023-06-30" },
  { name: "Christmas Island", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Clipperton Island", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Coahuila", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Cocos Islands", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Colima", level: 4, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Colombia", level: 3, higherRiskAreas: true, advisoryDate: "2024-01-02" },
  { name: "Comoros", level: 2, higherRiskAreas: false, advisoryDate: "2024-05-28" },
  { name: "Cook Islands", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Costa Rica", level: 2, higherRiskAreas: false, advisoryDate: "2023-07-17" },
  { name: "Côte d'Ivoire", level: 2, higherRiskAreas: true, advisoryDate: "2024-04-08" },
  { name: "Croatia", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-15" },
  { name: "Cuba", level: 3, higherRiskAreas: false, advisoryDate: "2024-11-05" },
  { name: "Curaçao", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-19" },
  { name: "Cyprus", level: 1, higherRiskAreas: false, advisoryDate: "2023-07-26" },
  { name: "Czech Republic", level: 1, higherRiskAreas: false, advisoryDate: "2023-07-26" },
  { name: "Democratic Republic of the Congo", level: 3, higherRiskAreas: false, advisoryDate: "2024-07-09" },
  { name: "Denmark", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-17" },
  { name: "Djibouti", level: 2, higherRiskAreas: true, advisoryDate: "2023-07-31" },
  { name: "Dominica", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-22" },
  { name: "Dominican Republic", level: 2, higherRiskAreas: false, advisoryDate: "2024-06-18" },
  { name: "Durango", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Ecuador", level: 2, higherRiskAreas: true, advisoryDate: "2024-03-08" },
  { name: "Egypt", level: 3, higherRiskAreas: true, advisoryDate: "2024-10-15" },
  { name: "El Salvador", level: 2, higherRiskAreas: false, advisoryDate: "2024-11-08" },
  { name: "Equatorial Guinea", level: 2, higherRiskAreas: false, advisoryDate: "2024-04-04" },
  { name: "Eritrea", level: 2, higherRiskAreas: false, advisoryDate: "2023-07-31" },
  { name: "Estonia", level: 1, higherRiskAreas: false, advisoryDate: "2024-07-23" },
  { name: "Eswatini", level: 2, higherRiskAreas: false, advisoryDate: "2024-07-01" },
  { name: "Ethiopia", level: 3, higherRiskAreas: true, advisoryDate: "2023-07-31" },
  { name: "Falkland Islands", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Faroe Islands", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Fiji", level: 1, higherRiskAreas: false, advisoryDate: "2023-08-09" },
  { name: "Finland", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-09" },
  { name: "France", level: 2, higherRiskAreas: false, advisoryDate: "2023-07-26" },
  { name: "French Guiana", level: 1, higherRiskAreas: false, advisoryDate: "2023-07-17" },
  { name: "French Polynesia", level: 1, higherRiskAreas: false, advisoryDate: "2023-07-25" },
  { name: "French Southern Territories", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Gabon", level: 1, higherRiskAreas: true, advisoryDate: "2023-07-31" },
  { name: "Gaza Strip", level: 4, higherRiskAreas: false, advisoryDate: "2024-07-31" },
  { name: "Georgia", level: 1, higherRiskAreas: false, advisoryDate: "2023-07-26" },
  { name: "Germany", level: 2, higherRiskAreas: false, advisoryDate: "2024-05-01" },
  { name: "Ghana", level: 2, higherRiskAreas: false, advisoryDate: "2023-11-20" },
  { name: "Gibraltar", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Glorioso Islands", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Greece", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-15" },
  { name: "Greenland", level: 2, higherRiskAreas: false, advisoryDate: "2024-10-29" },
  { name: "Grenada", level: 1, higherRiskAreas: false, advisoryDate: "2024-11-12" },
  { name: "Guadeloupe", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-22" },
  { name: "Guam", level: 1, higherRiskAreas: false, advisoryDate: null },
  { name: "Guanajuato", level: 3, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Guatemala", level: 3, higherRiskAreas: true, advisoryDate: "2023-07-17" },
  { name: "Guernsey", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Guerrero", level: 4, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Guinea", level: 3, higherRiskAreas: false, advisoryDate: "2023-12-26" },
  { name: "Guinea-Bissau", level: 3, higherRiskAreas: false, advisoryDate: "2024-07-31" },
  { name: "Guyana", level: 3, higherRiskAreas: false, advisoryDate: "2023-07-17" },
  { name: "Haiti", level: 4, higherRiskAreas: false, advisoryDate: "2023-09-18" },
  { name: "Heard Island and McDonald Islands", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Hidalgo", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Honduras", level: 3, higherRiskAreas: true, advisoryDate: "2023-07-17" },
  { name: "Hong Kong", level: 2, higherRiskAreas: false, advisoryDate: "2024-04-12" },
  { name: "Hungary", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-21" },
  { name: "Iceland", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-22" },
  { name: "India", level: 2, higherRiskAreas: true, advisoryDate: "2024-07-23" },
  { name: "Indonesia", level: 2, higherRiskAreas: true, advisoryDate: "2023-07-25" },
  { name: "Iran", level: 4, higherRiskAreas: false, advisoryDate: "2024-08-14" },
  { name: "Iraq", level: 4, higherRiskAreas: false, advisoryDate: "2023-10-22" },
  { name: "Ireland", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-28" },
  { name: "Isle of Man", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Israel", level: 3, higherRiskAreas: true, advisoryDate: "2024-07-31" },
  { name: "Italy", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-12" },
  { name: "Jalisco", level: 3, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Jamaica", level: 3, higherRiskAreas: true, advisoryDate: "2024-07-25" },
  { name: "Jan Mayen", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Japan", level: 1, higherRiskAreas: false, advisoryDate: "2024-01-08" },
  { name: "Jersey", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Jordan", level: 2, higherRiskAreas: true, advisoryDate: "2024-09-11" },
  { name: "Juan de Nova Island", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Kazakhstan", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-05" },
  { name: "Kenya", level: 2, higherRiskAreas: true, advisoryDate: "2023-07-31" },
  { name: "Kiribati", level: 1, higherRiskAreas: false, advisoryDate: "2023-08-09" },
  { name: "Kosovo", level: 2, higherRiskAreas: true, advisoryDate: "2023-07-26" },
  { name: "Kuwait", level: 1, higherRiskAreas: false, advisoryDate: "2023-07-13" },
  { name: "Kyrgyzstan", level: 1, higherRiskAreas: true, advisoryDate: "2024-03-08" },
  { name: "Laos", level: 2, higherRiskAreas: true, advisoryDate: "2023-07-25" },
  { name: "Latvia", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-26" },
  { name: "Lebanon", level: 4, higherRiskAreas: false, advisoryDate: "2024-09-28" },
  { name: "Lesotho", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-17" },
  { name: "Liberia", level: 2, higherRiskAreas: false, advisoryDate: "2023-07-31" },
  { name: "Libya", level: 4, higherRiskAreas: false, advisoryDate: "2024-08-01" },
  { name: "Liechtenstein", level: 1, higherRiskAreas: false, advisoryDate: "2022-10-04" },
  { name: "Lithuania", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-09" },
  { name: "Luxembourg", level: 1, higherRiskAreas: false, advisoryDate: "2022-10-04" },
  { name: "Macau", level: 3, higherRiskAreas: false, advisoryDate: "2024-04-12" },
  { name: "Madagascar", level: 2, higherRiskAreas: false, advisoryDate: "2024-11-05" },
  { name: "Madeira Islands", level: 3, higherRiskAreas: false, advisoryDate: "2021-06-17" },
  { name: "Malawi", level: 2, higherRiskAreas: false, advisoryDate: "2023-07-31" },
  { name: "Malaysia", level: 1, higherRiskAreas: true, advisoryDate: "2023-07-25" },
  { name: "Maldives", level: 2, higherRiskAreas: false, advisoryDate: "2024-07-11" },
  { name: "Mali", level: 4, higherRiskAreas: false, advisoryDate: "2023-07-31" },
  { name: "Malta", level: 1, higherRiskAreas: false, advisoryDate: "2023-07-26" },
  { name: "Marshall Islands", level: 1, higherRiskAreas: false, advisoryDate: "2024-05-28" },
  { name: "Martinique", level: 1, higherRiskAreas: false, advisoryDate: "2022-04-18" },
  { name: "Mauritania", level: 3, higherRiskAreas: true, advisoryDate: "2023-07-31" },
  { name: "Mauritius", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-30" },
  { name: "Mayotte", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "México", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Mexico City", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Michoacán", level: 4, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Micronesia", level: 1, higherRiskAreas: false, advisoryDate: "2023-07-25" },
  { name: "Moldova", level: 3, higherRiskAreas: true, advisoryDate: "2024-09-19" },
  { name: "Monaco", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Mongolia", level: 1, higherRiskAreas: false, advisoryDate: "2023-07-25" },
  { name: "Montenegro", level: 1, higherRiskAreas: false, advisoryDate: "2022-10-04" },
  { name: "Montserrat", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-22" },
  { name: "Morelos", level: 3, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Morocco", level: 2, higherRiskAreas: false, advisoryDate: "2023-07-13" },
  { name: "Mozambique", level: 2, higherRiskAreas: true, advisoryDate: "2023-07-31" },
  { name: "Namibia", level: 2, higherRiskAreas: false, advisoryDate: "2023-11-27" },
  { name: "Nauru", level: 1, higherRiskAreas: false, advisoryDate: "2023-07-25" },
  { name: "Nayarit", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Nepal", level: 2, higherRiskAreas: false, advisoryDate: "2023-06-23" },
  { name: "Netherlands", level: 2, higherRiskAreas: false, advisoryDate: "2024-08-09" },
  { name: "New Caledonia", level: 3, higherRiskAreas: false, advisoryDate: "2024-06-04" },
  { name: "New Zealand", level: 1, higherRiskAreas: false, advisoryDate: "2023-09-08" },
  { name: "Nicaragua", level: 3, higherRiskAreas: false, advisoryDate: "2024-01-11" },
  { name: "Niger", level: 3, higherRiskAreas: true, advisoryDate: "2024-01-08" },
  { name: "Nigeria", level: 3, higherRiskAreas: true, advisoryDate: "2023-09-20" },
  { name: "Niue", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Norfolk Island", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "North Korea", level: 4, higherRiskAreas: false, advisoryDate: "2023-07-24" },
  { name: "North Macedonia", level: 1, higherRiskAreas: false, advisoryDate: "2022-10-04" },
  { name: "Northern Mariana Islands", level: 1, higherRiskAreas: false, advisoryDate: null },
  { name: "Norway", level: 1, higherRiskAreas: false, advisoryDate: "2022-10-04" },
  { name: "Nuevo León", level: 2, higherRiskAreas: false, advisoryDate: "2023-08-22" },
  { name: "Oaxaca", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Oman", level: 2, higherRiskAreas: false, advisoryDate: "2024-11-04" },
  { name: "Pakistan", level: 3, higherRiskAreas: true, advisoryDate: "2024-09-10" },
  { name: "Palau", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-06" },
  { name: "Panama", level: 2, higherRiskAreas: true, advisoryDate: "2024-09-23" },
  { name: "Papua New Guinea", level: 3, higherRiskAreas: true, advisoryDate: "2024-01-17" },
  { name: "Paraguay", level: 1, higherRiskAreas: true, advisoryDate: "2023-07-17" },
  { name: "Peru", level: 2, higherRiskAreas: false, advisoryDate: "2023-11-15" },
  { name: "Philippines", level: 2, higherRiskAreas: true, advisoryDate: "2022-10-05" },
  { name: "Pitcairn Islands", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Poland", level: 1, higherRiskAreas: false, advisoryDate: "2024-05-01" },
  { name: "Portugal", level: 1, higherRiskAreas: false, advisoryDate: "2022-10-04" },
  { name: "Puebla", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Puerto Rico", level: 1, higherRiskAreas: false, advisoryDate: null },
  { name: "Qatar", level: 1, higherRiskAreas: false, advisoryDate: "2023-07-13" },
  { name: "Querétaro", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Quintana Roo", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Republic of the Congo", level: 2, higherRiskAreas: false, advisoryDate: "2024-10-02" },
  { name: "Réunion", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Romania", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-15" },
  { name: "Russia", level: 4, higherRiskAreas: false, advisoryDate: "2024-06-27" },
  { name: "Rwanda", level: 3, higherRiskAreas: true, advisoryDate: "2024-10-07" },
  { name: "Saba", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-19" },
  { name: "Saint Barthelemy", level: 1, higherRiskAreas: false, advisoryDate: "2024-06-27" },
  { name: "Saint Helena", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Saint Kitts and Nevis", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-22" },
  { name: "Saint Lucia", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-22" },
  { name: "Saint Martin", level: 1, higherRiskAreas: false, advisoryDate: "2022-10-05" },
  { name: "Saint Pierre and Miquelon", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Saint Vincent and the Grenadines", level: 1, higherRiskAreas: false, advisoryDate: "2024-11-12" },
  { name: "Samoa", level: 1, higherRiskAreas: false, advisoryDate: "2023-07-24" },
  { name: "San Luis Potosí", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "San Marino", level: 2, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Sao Tome and Principe", level: 1, higherRiskAreas: false, advisoryDate: "2024-09-25" },
  { name: "Saudi Arabia", level: 2, higherRiskAreas: true, advisoryDate: "2024-09-09" },
  { name: "Senegal", level: 1, higherRiskAreas: true, advisoryDate: "2024-10-21" },
  { name: "Serbia", level: 2, higherRiskAreas: false, advisoryDate: "2022-10-04" },
  { name: "Seychelles", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-30" },
  { name: "Sierra Leone", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-23" },
  { name: "Sinaloa", level: 4, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Singapore", level: 1, higherRiskAreas: false, advisoryDate: "2023-07-24" },
  { name: "Sint Eustatius", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-19" },
  { name: "Sint Maarten", level: 1, higherRiskAreas: false, advisoryDate: "2024-08-19" },
  { name: "Slovakia", level: 1, higherRiskAreas: false, advisoryDate: "2024-11-14" },
  { name: "Slovenia", level: 1, higherRiskAreas: false, advisoryDate: "2024-07-26" },
  { name: "Solomon Islands", level: 2, higherRiskAreas: false, advisoryDate: "2022-10-05" },
  { name: "Somalia", level: 4, higherRiskAreas: false, advisoryDate: "2024-07-23" },
  { name: "Sonora", level: 3, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "South Africa", level: 2, higherRiskAreas: false, advisoryDate: "2024-11-07" },
  { name: "South Georgia and the South Sandwich Islands", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "South Korea", level: 1, higherRiskAreas: false, advisoryDate: "2023-07-24" },
  { name: "South Sudan", level: 4, higherRiskAreas: false, advisoryDate: "2023-07-31" },
  { name: "Spain", level: 2, higherRiskAreas: false, advisoryDate: "2022-10-04" },
  { name: "Sri Lanka", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-12" },
  { name: "Sudan", level: 4, higherRiskAreas: false, advisoryDate: "2023-04-22" },
  { name: "Suriname", level: 1, higherRiskAreas: false, advisoryDate: "2023-07-17" },
  { name: "Svalbard", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Sweden", level: 1, higherRiskAreas: false, advisoryDate: "2022-10-04" },
  { name: "Switzerland", level: 1, higherRiskAreas: false, advisoryDate: "2022-10-04" },
  { name: "Syria", level: 4, higherRiskAreas: false, advisoryDate: "2023-07-13" },
  { name: "Tabasco", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Taiwan", level: 1, higherRiskAreas: false, advisoryDate: "2024-07-31" },
  { name: "Tajikistan", level: 2, higherRiskAreas: true, advisoryDate: "2023-11-27" },
  { name: "Tamaulipas", level: 4, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Tanzania", level: 2, higherRiskAreas: true, advisoryDate: "2024-09-05" },
  { name: "Thailand", level: 1, higherRiskAreas: true, advisoryDate: "2022-10-05" },
  { name: "The Bahamas", level: 2, higherRiskAreas: false, advisoryDate: "2024-01-26" },
  { name: "The Gambia", level: 2, higherRiskAreas: false, advisoryDate: "2024-10-16" },
  { name: "Timor-Leste", level: 2, higherRiskAreas: false, advisoryDate: "2022-10-05" },
  { name: "Tlaxcala", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Togo", level: 2, higherRiskAreas: true, advisoryDate: "2024-11-07" },
  { name: "Tokelau", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Tonga", level: 1, higherRiskAreas: false, advisoryDate: "2022-11-08" },
  { name: "Trinidad and Tobago", level: 3, higherRiskAreas: false, advisoryDate: "2024-07-02" },
  { name: "Tunisia", level: 2, higherRiskAreas: true, advisoryDate: "2024-10-23" },
  { name: "Turkey", level: 2, higherRiskAreas: false, advisoryDate: "2022-10-04" },
  { name: "Turkmenistan", level: 2, higherRiskAreas: false, advisoryDate: "2023-06-23" },
  { name: "Turks and Caicos Islands", level: 2, higherRiskAreas: false, advisoryDate: "2023-07-17" },
  { name: "Tuvalu", level: 1, higherRiskAreas: false, advisoryDate: "2023-08-09" },
  { name: "U.S. Virgin Islands", level: 1, higherRiskAreas: false, advisoryDate: null },
  { name: "Uganda", level: 3, higherRiskAreas: false, advisoryDate: "2024-10-21" },
  { name: "Ukraine", level: 4, higherRiskAreas: false, advisoryDate: "2024-11-14" },
  { name: "United Arab Emirates", level: 2, higherRiskAreas: false, advisoryDate: "2023-07-13" },
  { name: "United Kingdom", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-03" },
  { name: "United States", level: 1, higherRiskAreas: false, advisoryDate: "2018-11-01" },
  { name: "United States Minor Outlying Islands", level: 1, higherRiskAreas: false, advisoryDate: null },
  { name: "Uruguay", level: 2, higherRiskAreas: false, advisoryDate: "2023-07-17" },
  { name: "Uzbekistan", level: 1, higherRiskAreas: false, advisoryDate: "2024-09-27" },
  { name: "Vanuatu", level: 1, higherRiskAreas: false, advisoryDate: "2022-10-11" },
  { name: "Vatican City", level: 2, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "Venezuela", level: 4, higherRiskAreas: false, advisoryDate: "2024-09-24" },
  { name: "Veracruz", level: 2, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Vietnam", level: 1, higherRiskAreas: false, advisoryDate: "2022-10-05" },
  { name: "Wallis and Futuna", level: 1, higherRiskAreas: false, advisoryDate: "2018-01-11" },
  { name: "West Bank", level: 3, higherRiskAreas: true, advisoryDate: "2024-07-31" },
  { name: "Yemen", level: 4, higherRiskAreas: false, advisoryDate: "2024-07-10" },
  { name: "Yucatán", level: 1, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Zacatecas", level: 4, higherRiskAreas: false, advisoryDate: "2024-09-06" },
  { name: "Zambia", level: 1, higherRiskAreas: false, advisoryDate: "2022-10-05" },
  { name: "Zimbabwe", level: 2, higherRiskAreas: false, advisoryDate: "2023-06-27" },
];
